name: Build and deploy

on:
  # push:
  #   branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


        # TFLint - Terraform Check
      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          github_token: ${{ secrets.CI_GITHUB_TOKEN }}

      # Print TFLint version
      - name: Show version
        run: tflint --version

      # Install plugins
      - name: Init TFLint
        run: tflint --init

      # Run tflint command in each directory recursively # use --force if you want to continue with workflow although errors are there
      - name: Run TFLint
        run: tflint -f compact --chdir ${{ github.workspace }}/infra

      # Checkov - Prevent cloud misconfigurations and find vulnerabilities during build-time in infrastructure as code
      - name: Run Checkov
        run: |
            docker run -t -v ${{ github.workspace }}/infra:/tf --workdir /tf bridgecrew/checkov --directory /tf --quiet
        continue-on-error: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check and Copy to S3 Buckets
        run: |
          check_and_copy() {
            BUCKET_NAME=$1
            if aws s3 ls "s3://$BUCKET_NAME" 2>&1 | grep -q 'NoSuchBucket'; then
              echo "Bucket $BUCKET_NAME does not exist."
            else
              echo "Bucket $BUCKET_NAME exists. Copying files..."
              aws s3 cp --recursive site/ "s3://$BUCKET_NAME/"
            fi
          }

          check_and_copy "${{ secrets.S3_BUCKET }}"
          check_and_copy "${{ secrets.REDIRECT_S3_BUCKET }}"
